### ISSUE TITLE
No autoformatting config

### ISSUE THREAD

**Issue by dwarez** [hendrikmi/neovim-kickstart-config#1]
Hey Hendrik,
thanks for the great tutorial :smile: 

I noticed that the repository is missing the `autoformatting.lua` file. Could you provide it?
I tried to copy the content showed in the video and, even if the plugin seems correctly installed, it's not formatting on save. 

Thanks!

**Comment by hendrikmi** [comment]
Hi, Thanks I really appreciate the feedback. Glad it was helpful :)

In this repo I named the file `none-ls.lua` because none-ls can do more than autoformatting. 

Feel free to share your config if it still doesn't work.

**Comment by dwarez** [comment]
> Hi, Thanks I really appreciate the feedback. Glad it was helpful :)
> 
> In this repo I named the file `none-ls.lua` because none-ls can do more than autoformatting.
> 
> Feel free to share your config if it still doesn't work.

Damn, I totally missed it, thanks! :grin:
