### ISSUE TITLE
grep feature isn't working

### ISSUE THREAD

**Issue by osimkin** [hendrikmi/neovim-kickstart-config#4]
Hi, hendrikmi,

After watching an excellent youtube tutorial, I decided to work with neovim.
**My setup:**
Ubuntu: VERSION="22.04.5 LTS (Jammy Jellyfish)"
NVIM v0.10.2
1. Cloned your entire repo "neovim-kickstart-config" into ~/.config/nvim.
2. Open init.lua with nvim. Most of plugins have been installed except sqlls. However that very plugin is not critical for me now.
**The issue:**
invoking grep with <leader>sw or <leader>sg brings grep window, yet the search isnt producing any result in both cases (<leader>sw and <leader>sg). Additionally, an error is shown at the bottom. See the screenshot.
Would you mind suggesting how to address this issue?
![grep_search](https://github.com/user-attachments/assets/7f462fe9-a65d-4a5e-959c-415a335b22f6)

**Comment by hendrikmi** [comment]
Hi, thanks for bringing this up! I think this might be related to Telescope. Do you have ripgrep installed on your system?Telescope's `live_grep` function depends on it (see [here](https://github.com/nvim-telescope/telescope.nvim/tree/master?tab=readme-ov-file#file-pickers)).

**Comment by osimkin** [comment]
Hi, hendrikmi,

No files have been changed after I cloned the repo to local machine. 
There are two references to "live_grep". Both are in lua/plugins/telescope.lua.
As far as I can say, yes, live_grep has been installed. 
Refer to two images below. Please suggest. 
![live_grep](https://github.com/user-attachments/assets/050d6f45-88db-4296-8dcd-abede445e176)
![live_grep_map](https://github.com/user-attachments/assets/63cb51df-b782-4070-b067-941926a9e6f2)

**Comment by hendrikmi** [comment]
The thing is that `live_grep` depends on ripgrep to be installed on your machine. Can you successfully run `rg --version` in your terminal?

**Comment by osimkin** [comment]
Hi hendrikmi,

Yes, that was a root cause. My Ubuntu didn't have "ripgrep" installed. After the install, I have chosen latest version 13.0.0, grep search within nvim started working as expected. Thank you for the swift responses. 
I will close the issue now.

**Comment by osimkin** [comment]
The issue was addressed. Thank you

**Comment by osimkin** [comment]
The issue was addressed. Thank you

**Comment by hendrikmi** [comment]
Happy to hear that. Take care! 🙂

**Comment by hendrikmi** [comment]
Happy to hear that. Take care! 🙂
